INSERT INTO suggestions (term, popularity) VALUES
  ('ação civil pública', 95),
  ('ação de alimentos', 90),
  ('ação de cobrança', 85),
  ('ação de despejo', 80),
  ('ação de indenização', 100),
  ('ação de obrigação de fazer', 88),
  ('ação de usucapião', 75),
  ('ação anulatória', 74),
  ('ação cautelar', 73),
  ('ação declaratória', 86),
  ('ação demarcatória', 52),
  ('ação direta de inconstitucionalidade', 81),
  ('ação divisória', 51),
  ('ação eleitoral', 58),
  ('ação monitória', 84),
  ('ação negatória de paternidade', 61),
  ('ação penal privada', 67),
  ('ação popular', 79),
  ('ação possessória', 89),
  ('ação regressiva', 64),
  ('ação renovatória', 69),
  ('ação rescisória', 83),
  ('ação revisional', 91),
  ('ação trabalhista', 96),
  ('ação tributária', 72),
  ('ação de adjudicação compulsória', 77),
  ('ação de busca e apreensão', 85),
  ('ação de consignação em pagamento', 80),
  ('ação de dissolução de sociedade', 63),
  ('ação de execução', 94),
  ('ação de exigir contas', 76),
  ('ação de guarda', 87),
  ('ação de imissão na posse', 71),
  ('ação de investigação de paternidade', 82),
  ('ação de nunciação de obra nova', 50),
  ('ação de prestação de contas', 78),
  ('ação de reconhecimento de união estável', 90),
  ('ação de reintegração de posse', 93),
  ('ação de repetição de indébito', 88),
  ('ação de revisão contratual', 92),
  ('ação de tutela', 70),
  ('ação indenizatória por erro médico', 97),
  ('acidente de trabalho', 92),
  ('acordo extrajudicial', 70),
  ('adicional de insalubridade', 78),
  ('adicional de periculosidade', 72),
  ('alienação fiduciária', 68),
  ('alimentos gravídicos', 65),
  ('aposentadoria especial', 94),
  ('aposentadoria por idade', 91),
  ('aposentadoria por invalidez', 89),
  ('assédio moral', 98),
  ('auxílio-acidente', 82),
  ('auxílio-doença', 87),
  ('busca e apreensão', 84),
  ('contrato de locação', 76),
  ('danos materiais', 96),
  ('danos morais', 110),
  ('demissão por justa causa', 73),
  ('direito do consumidor', 105),
  ('divórcio consensual', 86),
  ('divórcio litigioso', 83),
  ('execução de alimentos', 81),
  ('guarda compartilhada', 93),
  ('habeas corpus', 99),
  ('inventário extrajudicial', 77),
  ('inventário judicial', 74),
  ('medida protetiva', 97),
  ('pensão alimentícia', 108),
  ('rescisão contratual', 79),
  ('revisão de benefício', 71),
  ('seguro-desemprego', 69),
  ('usucapião extraordinária', 67),
  ('usucapião urbana', 66),
  ('violência doméstica', 102)
ON CONFLICT (term) DO NOTHING;
