INSERT INTO suggestions (term, popularity) VALUES
  ('ação civil pública', 95),
  ('ação de alimentos', 90),
  ('ação de cobrança', 85),
  ('ação de despejo', 80),
  ('ação de indenização', 100),
  ('ação de obrigação de fazer', 88),
  ('ação de usucapião', 75),
  ('acidente de trabalho', 92),
  ('acordo extrajudicial', 70),
  ('adicional de insalubridade', 78),
  ('adicional de periculosidade', 72),
  ('alienação fiduciária', 68),
  ('alimentos gravídicos', 65),
  ('aposentadoria especial', 94),
  ('aposentadoria por idade', 91),
  ('aposentadoria por invalidez', 89),
  ('assédio moral', 98),
  ('auxílio-acidente', 82),
  ('auxílio-doença', 87),
  ('busca e apreensão', 84),
  ('contrato de locação', 76),
  ('danos materiais', 96),
  ('danos morais', 110),
  ('demissão por justa causa', 73),
  ('direito do consumidor', 105),
  ('divórcio consensual', 86),
  ('divórcio litigioso', 83),
  ('execução de alimentos', 81),
  ('guarda compartilhada', 93),
  ('habeas corpus', 99),
  ('inventário extrajudicial', 77),
  ('inventário judicial', 74),
  ('medida protetiva', 97),
  ('pensão alimentícia', 108),
  ('rescisão contratual', 79),
  ('revisão de benefício', 71),
  ('seguro-desemprego', 69),
  ('usucapião extraordinária', 67),
  ('usucapião urbana', 66),
  ('violência doméstica', 102)
ON CONFLICT (term) DO NOTHING;
