CREATE TABLE IF NOT EXISTS suggestions (
  id SERIAL PRIMARY KEY,
  term VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_suggestions_term
ON suggestions (term);
